version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      args:
        RESEND_API_KEY: ${RESEND_API_KEY}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    ports:
      - "3010:3000"  # Now expose to host directly
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
