version: '3.8'

services:
  nextjs-app:
    build: .
    expose:
      - "3000"  # Only expose to internal network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Cloudflare will handle SSL and proxy to port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs-app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge